config/routes.rb
Rails.application.routes.draw do

  root to: 'index#home_page'

    #Controller_Index
  get '/', to: 'index#home_page'
  get '/register', to: 'user#new'
  get '/sign_in', to: 'index#sign_in_page'
  post '/register', to: 'index#home_page'
  get '/team', to: 'index#team_page'
  get '/contact', to: 'index#contact_page'


    #Controller_User
  #get '/user/:id', to: 'user#user_entry_page'
  #get '/user/:id', to: 'user#show'
  resources :user


    #Controller_Gossip
  resources :gossip do
    resources :comment
  end

  
    #Controller_City
  resources :city
    

    #Controller_Comment
  resources :comment

    #Controller_Session
  resources :session

end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :affiliations, dependent: :destroy 
    has_many :tags, through: :affiliations
    has_many :comments



end












    

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :affiliations
    has_many :gossips, through: :affiliations
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips

    has_secure_password


    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/city_controller.rb
class CityController < ApplicationController

    def show
        @city = City.find(params[:id])
    end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

    def new
        #@gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.new
    end

    def create
        @comment = Comment.new(
            'content' => params[:content],
            'gossip_id' => params[:gossip_id]
            )
        if @comment.save 
            redirect_to gossip_path(@gossip.id)
        end
    end

    def show
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

    def new
        @gossip = Gossip.new
    end
    
    def create
        @gossip = Gossip.new(
            'title' => params[:title], 
            'content'=> params[:content],
            'user_id' => User.all.sample.id
            )
        if @gossip.save
            redirect_to "/"
        end
    end

    def new_is_ok
    end

    def show
        @gossip = Gossip.find(params[:id])
        @comments = Comment.all  
    end

    def edit
        @gossip = Gossip.find(params[:id])
    end

    def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(
            'title' => params[:title],
            'content' => params[:content]
            )
            redirect_to @gossip
        else
            render :edit
        end
    end

    def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to root_path
    end
    
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
   
    def home_page
        @gossips = Gossip.all 
        @users = User.all  
    end

    def team_page
    end

    def contact_page
    end

    def new
        @user = User.new
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            remember(user)
            redirect_to session_path(id: session[:user_id])
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])

    end

    def destroy
        session.delete(:user_id)
        redirect_to gossips_path
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def user_entry_page 
        @first_name = params[:id]     
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(
            'first_name' => params[:first_name], 
            'last_name' => params[:last_name],
            'email' => params[:email],
            'age' => params[:age],
            'city_id' => params[:city],
            'description' => params[:description],
            'password' => params[:password_digest]
            )
        if @user.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def index
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
    end

    def udpdate
    end

    def destroy
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/session_helper.rb
module SessionHelper

    def remember(user)
        remember_token = SecureRandom.urlsafe_base64
        user.remember(remember_token)
        cookies.permanent[:user_id] = user.id
        cookies.permanent[:remember_token] = remember_token
    end

    def forget(user)
        user.update(remember_digest: nil)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out(user)
        session.delete(:user_id)
        forget(user)
      end
end

app/helpers/user_helper.rb
module UserHelper

    def current_user
        if session[:user_id]
            current_user = User.find_by(id: session[:user_id])
        elsif cookies[:user_id]
            user = User.find_by(id: cookies[:user_id])
            if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
            log_in user
            current_user = user
            end
        end
    end
end

app/views/city/show.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">City : <%= @city.name %></a>
            </div>
        </nav>
    </div>



    <div class="main">
        <p></p>
        <p><strong>Name</strong></p>
            <%= @city.name %>
        <p></p>
        <p><strong>Zip code</strong></p>
            <%= @city.name %>
        <p></p>
    </div>
</body>

app/views/comment/new.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Add a comment</a>
            </div>
        </nav>
    </div>    
    <div class="page content col-7">
        <%= form_tag url_for(action: 'create'), method: "post" do %>
            <%= label_tag 'Comment Area:' %>
            <%= text_area_tag 'comment' %>
            <%= submit_tag 'Post comment' %>
        <% end %>
    </div>
</body>

app/views/gossip/edit.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Update this Gossip</a>
            </div>
        </nav>
    </div>



    <div class="main">
        <div class="main">
            <div class="page content col-7">
                <%= form_tag url_for(action: 'update'), method: "patch" do %>
    
                <%= label_tag 'Gossip Title' %>
                <%= text_field_tag 'title', @gossip.title %>
            
                <%= label_tag 'Gossip Content' %>
                <%= text_area_tag 'content', @gossip.content %>
                  
                <%= submit_tag 'Update Gossip' %>
              
              <% end %>
            </div>
        </div>
    </div>
</body>

app/views/gossip/new.html.erb
<body>
    <div class="header"></div>
            <div class="title">
                <h1>The Gossip Project</h1>
                <div>
                    <h6>><a href="/">Home Page</h6></a>
                </div>
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Write a Gossip</a>
            </div>
        </nav>
    </div>

    <div class="main">
        <div class="page content col-7">
            <%= form_tag url_for(action: 'create'), method: "post" do %>

            <%= label_tag 'Gossip Title' %>
            <%= text_field_tag 'title', @gossip.title %>
          
            <%= label_tag 'Gossip Content' %>
            <%= text_area_tag 'content', @gossip.content %>
          
            
            <%= submit_tag 'Create Gossip' %>
          
          <% end %>
        </div>
    </div>
</body>

app/views/gossip/new_is_not_ok.html.erb
<body>
    <div class="header"></div>
            <div class="title">
                <h1>The Gossip Project</h1>
                <div>
                    <h6>><a href="/">Home Page</h6></a>
                </div>
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Write a Gossip</a>
            </div>
        </nav>
    </div>

    <div class="main">
        <div class="page content col-7">
            <%= form_tag url_for(action: 'create'), method: "post" do %>

            <%= label_tag 'Gossip Title' %>
            <%= text_field_tag 'title', @gossip.title %>
          
            <%= label_tag 'Gossip Content' %>
            <%= text_area_tag 'content', @gossip.content %>
          
          
            <%= submit_tag 'Create Gossip' %>
          
          <% end %>
        </div>
    </div>
</body>

app/views/gossip/new_is_ok.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Write a Gossip</a>
            </div>
        </nav>
        <div class=new_is_ok_banner>
            <h1>Your gossip was successfully created</h1>
        </div>

    </div>

    <div class="main">
    </div>
</body>

app/views/gossip/show.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Gossip n°: <%= @gossip.id %></a>
                <button class="btn btn-warning"><a href="<%= new_comment_path(@gossip.id) %>">Comment</a></button>
                <button class="btn btn-warning"><a href="<%= edit_gossip_path(@gossip.id) %>">Update</a></button>
                <button class="btn btn-warning"><a href="<%= gossip_path(@gossip.id) %>" data-confirm="êtes-vous sur?" data-method="DELETE">Delete</a></button>
            </div>
        </nav>
    </div>



    <div class="main">
        <div>
            <p><strong>Title</strong></p>
                <%= @gossip.title %>
            <p></p>
            <p><strong>Content</strong></p>
                <%= @gossip.content %>
            <br>
            <br>
            <br>
            <p><strong><em>From</em></strong></p>
            <a href="/user/<%= @gossip.user_id %>"><%= @gossip.user.first_name %> <%= @gossip.user.last_name %></a><br>
            <a href="<%= city_path(@gossip.user.city.id) %>"><em><%= @gossip.user.city.name %></em></a>
            <br>
            <br>        
            <br>
            <br>
        </div>
        <div>
            <hr>
            <p><strong>Comments list :</strong></p>

            <p><%= @comments.all.each do |comments| %></p>
            <p><%= comment.content %></p>
            <button class="btn btn-warning"><a href="<%= gossip_path(gossip.id) %>">like</button>     <button class="btn btn-warning"><a href="<%= gossip_path(gossip.id) %>">dislike</button>
            <p><% end %></p>
        </div>
    </div>
</body>

app/views/session/new.html.erb
<body>
    <div class="header"></div>
            <div class="title">
                <h1>The Gossip Project</h1>
                <div>
                    <h6>><a href="/">Home Page</h6></a>
                </div>
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Log in</a>
            </div>
        </nav>
    </div>

    <div class="main">
        <div class="page content col-7">
            <%= form_tag url_for(action: 'create'), method: "post" do %>

            <%= label_tag 'Email' %>
            <%= text_field_tag 'email'%>
          
            <%= label_tag 'Password' %>
            <%= text_area_tag 'password' %>
          
            
            <%= submit_tag 'Confirm' %>
          
          <% end %>
        </div>
    </div>
</body>

app/views/session/show.html.erb
<div class="header"></div>
    <div class="title">
        <h1>The Gossip Project</h1>
        <div>
            <h6>><a href="/">Home Page</h6></a>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand">Welcome <%= @user.first_name %> !</a>
        </div>
    </nav>
</div>

<div class="main"> 
    <button class="btn btn-warning"><a href="<%= root_path%>">Log out</a></button>
</div>

app/views/user/new.html.erb
<body>
    <div class="header"></div>
            <div class="title">
                <h1>The Gossip Project</h1>
                <div>
                    <h6>><a href="/">Home Page</h6></a>
                </div>
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Create your account</a>
            </div>
        </nav>
    </div>

    <div class="main">
        <div class="page content col-7">
            <%= form_tag url_for(action: 'create'), method: "post" do %>
                <%= label_tag 'First name' %>
                <%= text_field_tag 'first_name', @user.first_name %>
    
                <%= label_tag 'Last name' %>
                <%= text_field_tag 'last_name', @user.last_name %>
    
                <%= label_tag 'Age' %>
                <%= text_field_tag 'age', @user.age %>
    
                <%= label_tag 'City' %>
                <%= text_field_tag 'city', @user.city %>
              
                <%= label_tag 'Description' %>
                <%= text_area_tag 'description', @user.description %>
    
                <%= label_tag 'Email' %>
                <%= text_field_tag 'email', @user.email %>
    
                <%= label_tag 'Password' %>
                <%= text_field_tag 'password_digest', @user.password_digest %>
              
                <%= submit_tag 'Create account' %>
            <% end %>
        </div>
    </div>
</body>

app/views/user/show.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Auteur : <%= @user.first_name %> <%= @user.last_name %></a>
            </div>
        </nav>
    </div>



    <div class="main">
        <p></p>
        <p><strong>Last Name</strong></p>
            <%= @user.last_name %>
        <p></p>
        <p><strong>First Name</strong></p>
            <%= @user.first_name %>
        <p></p>
        <p><strong>Description</strong></p>
            <%= @user.description %>
        <p></p>
        <p><strong>Age</strong></p>
            <%= @user.age %>
        <p></p>
        <p><strong>E-mail</strong></p>
            <%= @user.email%>
        <p></p>
        <p><strong>City</strong></p>
            <a href="<%= city_path(@user.city.id) %>"><em><%= @user.city.name %></em></a>
    </div>
</body>