config/routes.rb
Rails.application.routes.draw do

  root to: 'index#home_page'

    #Controller_Index
  get '/', to: 'index#home_page'
  get '/register', to: 'user#new'
  get '/sign_in', to: 'index#sign_in_page'
  post '/register', to: 'index#home_page'
  get '/team', to: 'index#team_page'
  get '/contact', to: 'index#contact_page'


    #Controller_User
  #get '/user/:id', to: 'user#user_entry_page'
  #get '/user/:id', to: 'user#show'
  resources :user


    #Controller_Gossip
  resources :gossip do
    resources :comment
  end

  
    #Controller_City
  resources :city
    

    #Controller_Comment
  resources :comment

    #Controller_Session
  resources :session

end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :gossip
    belongs_to :user
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    has_many :affiliations, dependent: :destroy 
    has_many :tags, through: :affiliations
    has_many :comments



end












    

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :affiliations
    has_many :gossips, through: :affiliations
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :city
    has_many :gossips

    has_secure_password


    def remember(remember_token)
        remember_digest = BCrypt::Password.create(remember_token)
        self.update(remember_digest: remember_digest)
    end

end

app/controllers/city_controller.rb
class CityController < ApplicationController

    def show
        @city = City.find(params[:id])
    end

end

app/controllers/comment_controller.rb
class CommentController < ApplicationController

    def new
        #@gossip = Gossip.find(params[:gossip_id])
        @comment = Comment.new
    end

    def create
        @comment = Comment.new(
            'content' => params[:content],
            'gossip_id' => params[:gossip_id]
            )
        if @comment.save 
            redirect_to gossip_path(@gossip.id)
        end
    end

    def show
    end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

    def new
        @gossip = Gossip.new
    end
    
    def create
        @gossip = Gossip.new(
            'title' => params[:title], 
            'content'=> params[:content],
            'user_id' => User.all.sample.id
            )
        if @gossip.save
            redirect_to "/"
        end
    end

    def new_is_ok
    end

    def show
        @gossip = Gossip.find(params[:id])
        @comments = Comment.all  
    end

    def edit
        @gossip = Gossip.find(params[:id])
    end

    def update
        @gossip = Gossip.find(params[:id])
        if @gossip.update(
            'title' => params[:title],
            'content' => params[:content]
            )
            redirect_to @gossip
        else
            render :edit
        end
    end

    def destroy
        @gossip = Gossip.find(params[:id])
        @gossip.destroy
        redirect_to root_path
    end
    
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
   
    def home_page
        @gossips = Gossip.all 
        @users = User.all  
    end

    def team_page
    end

    def contact_page
    end

    def new
        @user = User.new
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            remember(user)
            redirect_to session_path(id: session[:user_id])
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])

    end

    def destroy
        session.delete(:user_id)
        redirect_to gossips_path
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    def user_entry_page 
        @first_name = params[:id]     
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(
            'first_name' => params[:first_name], 
            'last_name' => params[:last_name],
            'email' => params[:email],
            'age' => params[:age],
            'city_id' => params[:city],
            'description' => params[:description],
            'password' => params[:password_digest]
            )
        if @user.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def index
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
    end

    def udpdate
    end

    def destroy
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/session_helper.rb
module SessionHelper

    def remember(user)
        remember_token = SecureRandom.urlsafe_base64
        user.remember(remember_token)
        cookies.permanent[:user_id] = user.id
        cookies.permanent[:remember_token] = remember_token
    end

    def forget(user)
        user.update(remember_digest: nil)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out(user)
        session.delete(:user_id)
        forget(user)
      end
end

app/helpers/user_helper.rb
module UserHelper

    def current_user
        if session[:user_id]
            current_user = User.find_by(id: session[:user_id])
        elsif cookies[:user_id]
            user = User.find_by(id: cookies[:user_id])
            if user && BCrypt::Password.new(user.remember_digest).is_password?(cookies[:remember_token])
            log_in user
            current_user = user
            end
        end
    end
end

app/views/index/contact_page.html.erb
<body>
    <div class="header"></div>
        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">How to join us ?</a>
            </div>
        </nav>
    </div>

    <div class="main"> 
    </div>
</body>

app/views/index/home_page.html.erb
<body>
    <div class="header"></div>

        <div class="title">
            <h1>The Gossip Project</h1>
            <div>
                <h6>><a href="/">Home Page</h6></a>
            </div>
        </div>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <div>
                    <a class="navbar-brand" href="#">Be prepared.</a>
                </div>
                <div>
                    <ul>
                        <li><a href="<%=new_gossip_path%>">Write a Gossip.</a></li>
                        <li><a href="<%=new_user_path%>">Sign up</a></li>
                        <li><a href="<%=new_session_path%>">Sign in</a></li>
                        <li><a href="/team">Team</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <div class="main">
        <div class="accueil_text">
            <h2>Welcome in the Gossip World of The Hacking Project</h2>
        </div>

        <div>
            <h4>Here is the Updated Gossip List</h4>
            <hr> 

            <p><%= @gossips.all.each_with_index do |gossip, index|%></p>
                <p><strong><%= gossip.user.first_name %> <%= gossip.user.last_name %></strong></p> 
                <p><%= gossip.title %></p> 
                <p><%= gossip.content %></p>
                <button class="btn btn-warning"><a href="<%= gossip_path(gossip.id) %>">Open this Gossip</button>
            <hr>  
            <p><% end %></p>
        </div>
    </div>
</body>

app/views/index/team_page.html.erb
<body>
    <div class="header"></div>
            <div class="title">
                <h1>The Gossip Project</h1>
                <div>
                    <h6>><a href="/">Home Page</h6></a>
                </div>
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand" href="#">Who are we ?</a>
            </div>
        </nav>
    </div>

    <div class="main">
        <br>
        <br>
        <br>
        <br>
        <br>
    <div class="row row-cols-1 row-cols-md-3 g-4">
  <div class="col">
    <div class="card h-100">
        <img src='./../../assets/images/Terminator.png' alt='icon' />
      <div class="card-body">
        <h5 class="card-title">Samuel KHALIFA<br>
        _____aka. T-800</h5>
        <p class="card-text">Description.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">THP Student (Winter 2022)</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
        <img src='app/assets/images/0SS_117.png' alt='icon' />
      <div class="card-body">
        <h5 class="card-title">Lois KOUNINEF<br>
            <em>_____aka. OSS_117<em></h5>
        <p class="card-text">Description.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">THP Student (Winter 2022)</small>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card h-100">
        <img src='app/assets/images/Lostark.png' alt='icon' />
      <div class="card-body">
        <h5 class="card-title">Enzo BONNET<br>
            <em>_____aka. Lost_ARK<em></h5>
        <p class="card-text">Description.</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">THP Student (Winter 2022)</small>
      </div>
    </div>
  </div>
</div>

    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetGossip2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>